version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /tree/(.*)
  static_files: static/tree/\1
  upload: static/tree/.*
- url: /.*
  script: guestbook.app


libraries:
- name: webapp2
  version: latest